PermitRootLogin prohibit-password
PasswordAuthentication no
KbdInteractiveAuthentication no
PubkeyAuthentication yes
PermitEmptyPasswords no
UsePAM yes
AllowTcpForwarding yes
ClientAliveInterval 60
ClientAliveCountMax 3
